server/basket/urls.py
from django.urls import path
# Импортируем контроллеры из модуля .views
from .views import basket_list, add_to_basket


app_name = 'basket'

urlpatterns = [
    path('', basket_list, name='basket_list'),
    path('add/<int:item>/', add_to_basket, name='add_to_basket')
]

server/products/urls.py
from django.urls import path
from products.views import products_list, products_detail, product_create, product_update, product_delete


app_name = 'products'

urlpatterns = [
    path('<int:pk>/delete/', product_delete, name='delete_product'),
    path('<int:pk>/update/', product_update, name='update_product'),
    path('create/', product_create, name='create_product'),
    path('', products_list, name='list'),
    path('<int:pk>/', products_detail, name='detail')
]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('mainapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('basket/', include('basket.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/products/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    title = models.CharField(
        max_length=250
    )
    snippet = models.TextField(
        blank=True,
        null=True,
    )
    modified = models.DateTimeField(
        auto_now=True,
    )
    created = models.DateTimeField(
        auto_now_add=True,
    )

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(
        max_length=250
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    image = models.ForeignKey(
        'images.Image',
        on_delete=models.PROTECT
    )
    snippet = models.TextField(
        blank=True,
        null=True,
    )
    cost = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=0,
    )
    quantity = models.PositiveSmallIntegerField(
        default=0
    )
    modified = models.DateTimeField(
        auto_now=True,
    )
    created = models.DateTimeField(
        auto_now_add=True,
    )

    def __str__(self):
        return self.title

server/products/forms.py
from django.forms import ModelForm
from .models import Product


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = [
            'title', 'category', 'image', 'snippet', 'cost'
        ]

server/products/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.core.paginator import Paginator
from django.http import Http404, HttpRequest

import json
from .models import Product, Category
from .forms import ProductForm
from django.urls import reverse_lazy

# Create your views here.


def product_delete(request, pk):
    success_url = reverse_lazy('mainapp:main')
    obj = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        obj.delete()

        return redirect(success_url)

    return render(request, 'products/delete.html', {'obj': obj})


def product_update(request, pk):
    success_url = reverse_lazy('mainapp:main')

    # try:
    #     obj = Product.objects.get(id=pk)
    # except Exception as err:
    #     raise Http404
    obj = get_object_or_404(Product, pk=pk)

    form = ProductForm(instance=obj)

    if request.method == 'POST':
        form = ProductForm(
            request.POST,
            files=request.FILES,
            instance=obj
        )
        if form.is_valid():
            form.save()
            return redirect(success_url)

    return render(
        request,
        'products/update.html',
        {
            'form': form,
            'obj': obj
        }
    )


def product_create(request):
    form = ProductForm()
    success_url = reverse_lazy('mainapp:main')

    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(success_url)

    return render(request, 'products/create.html', {'form': form})


def products_list(request):

    # context = {}
    # with open('products/data/products.json', 'r', encoding='UTF-8') as file:
    #     context = json.load(file)
    #
    # return render(request, 'products/Catalogue.html', context)

    # query = Product.objects.all()
    # query = get_list_or_404(Product)[:10]

    selected_category = request.GET.get('category')
    if selected_category is not None:
        selected_category = int(selected_category)

    categories = get_list_or_404(Category)

    if selected_category is not None:
        query = Product.objects.filter(category_id=selected_category)
        page = request.GET.get('page')
        paginator = Paginator(query, 10)
        products = paginator.get_page(page)
    else:
        query = get_list_or_404(Product)
        page = request.GET.get('page')
        paginator = Paginator(query, 10)
        products = paginator.get_page(page)

    if request.method == 'POST':
        requested_category_id = request.POST.get('product_category')
        query = Product.objects.filter(category_id=requested_category_id)
        selected_category = int(requested_category_id)
        page = request.GET.get('page')
        paginator = Paginator(query, 10)
        products = paginator.get_page(page)

        return render(
            request,
            'products/Catalogue.html',
            {
                'products': products,
                'categories': categories,
                'selected_category': selected_category
            }
        )

    return render(
        request,
        'products/Catalogue.html',
        {
            'products': products,
            'categories': categories,
            'selected_category': selected_category
        }
    )


def products_detail(request, pk):

    # context = {}
    # with open('products/data/products.json', 'r', encoding='UTF-8') as file:
    #     context = json.load(file)
    #
    # return render(
    #     request,
    #     'products/Product detail.html',
    #     {
    #         'object': context['products'][idx]
    #     }
    # )

    obj = Product.objects.get(pk=pk)

    return render(request, 'products/Product detail.html', {'product': obj})

server/products/templates/products/Catalogue.html
{% extends 'master.html' %}


{% block page_title %}
    Каталог товаров
{% endblock %}


{% block page_content %}
    <h3>Каталог изделий:</h3>
    <div class="items">
        {% for product in products %}
            {% include 'products/components/item.html' with image=product.image count=product.id name=product %}
        {% endfor %}
    </div>

    <ul class="pagination">
        {% if selected_category is not None %}
            {% if products.has_previous %}
            <li class="pagination__link_prev">
                <a href="?page={{ products.previous_page_number }}&category={{ selected_category }}">Предыдущая страница</a>
            </li>
            {% endif %}
            {% for num in products.paginator.page_range %}
            <li class="pagination__link_page">
                <a href="?page={{ num }}&category={{ selected_category }}">{{ num }}</a>
            </li>
            {% endfor %}
            {% if products.has_next %}
            <li class="pagination__link_next">
                <a href="?page={{ products.next_page_number }}&category={{ selected_category }}">Следующая страница</a>
            </li>
            {% endif %}
        {% else %}
            {% if products.has_previous %}
            <li class="pagination__link_prev">
                <a href="?page={{ products.previous_page_number }}">Предыдущая страница</a>
            </li>
            {% endif %}
            {% for num in products.paginator.page_range %}
            <li class="pagination__link_page">
                <a href="?page={{ num }}">{{ num }}</a>
            </li>
            {% endfor %}
            {% if products.has_next %}
            <li class="pagination__link_next">
                <a href="?page={{ products.next_page_number }}">Следующая страница</a>
            </li>
            {% endif %}
        {% endif %}
    </ul>

    <br>

    <form action="" method="POST" enctype="multipart/form-data">

        {% csrf_token %}

        <label for="id_category">
            Категория товаров:
        </label>
        <select onchange="submit()" name="product_category" id="id_category">
            <option value="" hidden>
                -------
            </option>
            {% for category in categories %}
                {% if category.id == selected_category %}
                <option value="{{ category.id }}" selected>
                    {{ category.title }}
                </option>
                {% else %}
                <option value="{{ category.id }}">
                    {{ category }}
                </option>
                {% endif %}
            {% endfor %}
        </select>
    </form>

    <div class="Empty"></div>
{% endblock %}

server/products/templates/products/Product detail.html
{% extends 'master.html' %}


{% block page_title %}
    {{ product }}
{% endblock %}


{% block page_content %}
    <h1>Описание товара</h1>
    <p>{{ product }}</p>
    <br>
    <h2>Характеристики товара</h2>
    <ul class="product_characteristics">
        <li><b>Размер регулируется</b></li>
        <li>Вощеная нить, производство Италия</li>
        <li>Цвета нитей и бусин в ассортименте</li>
    </ul>
    <br>
    <h3>Подробное описание товара</h3>
    <p>
        <a href="{{ product.image.url }}" target="_blank">
        <img src="{{ product.image.url }}" alt="Широкий браслет с агатом" width="300"></a><br>
    </p>

    <table>
        <tr>
            <td>Ширина:</td>
            <td>3.0 см</td>
        </tr>
        <tr>
            <td>Высота:</td>
            <td>регулируется</td>
        </tr>
        <tr>
            <td>Цвет:</td>
            <td>на Ваш выбор</td>
        </tr>
    </table>
    <br>
    <a href="{% url 'basket:add_to_basket' item=product.id %}">Добавить в корзину</a>

    <div class="Empty"></div>
{% endblock %}



<!--<!DOCTYPE html>-->
<!--<html lang="ru">-->

<!--<head>-->
    <!--<meta charset="UTF-8">-->
    <!--<title>Браслет в технике микромакраме</title>-->
    <!--<link rel="stylesheet" href="../css/style.css">-->
<!--</head>-->

<!--<body>-->
   <!--<div class="container">-->
       <!--<header>-->
           <!--<div id="logo">-->
    	    	<!--<img src="./img/logo.jpg" alt="Логотип">-->
           <!--</div>-->
            <!--<ul class="menu">-->
                <!--<li><a href="../index.html"><span class="lnr lnr-home"></span> Главная страница</a></li>-->
                <!--<li><a href="Catalogue.html"><span class="lnr lnr-book"></span> Каталог</a></li>-->
                <!--<li><a href="../Contacts.html"><span class="lnr lnr-phone"></span> Контакты</a></li>-->
            <!--</ul>-->
        <!--</header>-->
        <!--<hr>-->
        <!--<main>-->
            <!--<h1>Описание товара</h1>-->
            <!--<p>Широкий голубой браслет с агатом</p>-->
            <!--<br>-->
            <!--<h2>Характеристики товара</h2>-->
            <!--<ul class="product_characteristics">-->
                <!--<li><b>Ширина: 3.0 см</b></li>-->
                <!--<li><b>Размер регулируется</b></li>-->
                <!--<li>Вощеная нить, производство Италия</li>-->
                <!--<li>Цвета нитей и бусин в ассортименте</li>-->
            <!--</ul>-->
            <!--<br>-->
            <!--<h3>Подробное описание товара</h3>-->
            <!--<p>-->
                <!--<a href="../Catalogue/img/1.jpg" target="_blank"><img src="../Catalogue/img/1.jpg" alt="Широкий браслет с агатом" width="300"></a><br>-->
            <!--</p>-->
            <!---->
            <!--<table>-->
                <!--<tr>-->
                    <!--<td>Ширина:</td>-->
                    <!--<td>3.0 см</td>-->
                <!--</tr>-->
                <!--<tr>-->
                    <!--<td>Высота:</td>-->
                    <!--<td>регулируется</td>-->
                <!--</tr>-->
                <!--<tr>-->
                    <!--<td>Цвет:</td>-->
                    <!--<td>на Ваш выбор</td>-->
                <!--</tr>-->
            <!--</table>-->
            <!--<div class="Empty"></div>-->
        <!--</main>-->
        <!--<footer>-->
            <!--<hr>-->
            <!--<p>&copy; Все права защищены</p>-->
        <!--</footer>-->
   <!--</div>-->
<!--</body>-->
<!--</html>-->

server/products/templates/products/create.html
{% extends 'master.html' %}


{% block page_title %}
    Создать продукт
{% endblock %}


{% block page_content %}
    <h3>Создать продукт:</h3>
    <div class="New_product_form">
        {% include 'form.html' with form=form %}
    </div>
    <div class="Empty"></div>
{% endblock %}

server/products/templates/products/delete.html
{% extends 'master.html' %}


{% block page_title %}
    Удалить продукт: {{ obj.title }}
{% endblock %}


{% block page_content %}
    <h3>Удалить продукт:</h3>
    <form action="" method="POST">
        {% csrf_token %}

        {% if obj.category %}
        <h3>Вы действительно хотите удалить {{ obj.category }}, {{ obj.title }} ?</h3>
        {% else %}
        <h3>Вы действительно хотите удалить {{ obj.title }} ?</h3>
        {% endif %}
        <input type="submit" value="Delete">
    </form>
    <div class="Empty"></div>
{% endblock %}

server/products/templates/products/update.html
{% extends 'master.html' %}


{% block page_title %}
    Обновить продукт: {{ obj.title }}
{% endblock %}


{% block page_content %}
    <h3>Создать продукт:</h3>
    <div class="Edit_product_form">
        {% include 'form.html' with form=form %}
    </div>
    <div class="Empty"></div>
{% endblock %}