server/basket/urls.py
from django.urls import path
# Импортируем контроллеры из модуля .views
from .views import basket_list, add_to_basket


app_name = 'basket'

urlpatterns = [
    path('', basket_list, name='basket_list'),
    path('add/<int:item>/', add_to_basket, name='add_to_basket')
]

server/mainapp/urls.py
from django.urls import path
from mainapp.views import main, contacts

app_name = 'mainapp'

urlpatterns = [
    path('', main, name='main'),
    path('contacts/', contacts, name='contacts'),
]

server/products/urls.py
from django.urls import path
from products.views import products_list, products_detail, product_create, product_update, product_delete


app_name = 'products'

urlpatterns = [
    path('<int:pk>/delete/', product_delete, name='delete_product'),
    path('<int:pk>/update/', product_update, name='update_product'),
    path('create/', product_create, name='create_product'),
    path('', products_list, name='list'),
    path('<int:pk>/', products_detail, name='detail')
]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('mainapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('basket/', include('basket.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/server/templates/form.html
<form action="" method="POST" enctype="multipart/form-data">

    {% csrf_token %}

    {% for err in form.not_field_errors %}
    <div class="alert alert-danger" role="alert">
        <span>{{ err }}</span>
    </div>
    {% endfor %}

    {% for field in form %}
    <label for="{{ form.name }}">{{ field.label }}</label>
    {{ field }}

    {% for err in field.errors %}
    <small class="field_error">{{ err }}</small>
    {% endfor %}

    <!--<input type="text" placeholder="Имя"><br>-->
    <!--<input type="password" placeholder="Пароль"><br>-->
    <!--<input type="submit" value="Войти">-->
    <!--{{ form.as_table }}-->

    {% endfor %}
    <input type="submit" value="Enter">
</form>

server/server/templates/master.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block page_title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="/static/mainapp/css/style.css">
</head>
<body>
    <div class="container">
        <header>
            <div id="logo">
                <img src="/static/mainapp/img/logo.jpg" alt="Логотип" width="100">
            </div>
            <ul class="menu">
                <li><a href="{% url 'mainapp:main' %}"><span class="lnr lnr-home"></span> Главная страница</a></li>
                <li><a href="{% url 'products:list' %}"><span class="lnr lnr-book"></span> Каталог</a></li>
                <li><a href="{% url 'mainapp:contacts' %}"><span class="lnr lnr-phone"></span> Контакты</a></li>
            </ul>
        </header>
        <hr>
        <main>
            {% block page_content %}
            {% endblock %}
        </main>
        <footer>
            <hr>
    	    <p>&copy; Все права защищены</p>
        </footer>
    </div>
</body>
</html>